import Head from 'next/head';
import { AppProps } from 'next/app';
import Image from 'next/image';
import { useRouter } from 'next/router';
import Logo from '../assets/svg/logo.svg';
import '../styles/app.global.scss';

function App({ Component, pageProps }: AppProps) {
  const router = useRouter();

  const handleIconClick = () => {
    router.push('/');
  };

  return (
    <div className="app-container">
      <Head>
        <title>Coin State</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="main">
        <header className="header">
          <Image className="logo" src={Logo} alt="" onClick={handleIconClick} />
        </header>
        <Component {...pageProps} />
      </main>
    </div>
  );
}
export default App;
